server:
  servlet:
    context-path: /sys
  port: 8080
#web:
#  front:
#    baseDir: web_html
management:
  auditevents:
    enabled: false
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:7979/admin-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x_admin?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: wingzz00
  freemarker:
    suffix: .ftl
#    templateEncoding: UTF-8
    templateLoaderPath: file:D:/IdeaProjects/Xadmin/web_html/
    charset: UTF-8
    content-type: text/html;charset=UTF-8
#    default_encoding: UTF-8
    cache: false
    expose-session-attributes: true
    # 设置上下文路径
    request-context-attribute: request
  mvc:
    static-path-pattern: /assets/**
  resources:
    static-locations: file:D:/IdeaProjects/Xadmin/web_html/assets/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: wingzz00
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 100
        min-idle: 20
  cache:
    type: redis
  session:
    store-type: redis
    timeout: 86400 # Session 过期时间，单位s
#    redis:
#      flush-mode: # Sessions 刷新模式
#      namespace: # Namespace for keys used to store sessions.
mybatis:
  typeAliasesPackage: com.yao.sys.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
jwt:
  config:
    key: jsldkfuweio&*($@JHJBVDAYUIDhj
    ttl: 3600000
logging:
  config: D:/IdeaProjects/Xadmin/web_html/resources/log4j2-dev.xml
  level:
    com.yao.sys.dao: DEBUG

pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false
#公共权限每个人都有
interceptor:
  noVerify: /welcome,/index,/,/loginOut,/info/index,/info/resetpwd
