server:
  servlet:
    context-path: /httb
  port: 8080
management:
  auditevents:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ht_tb_data?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: wingzz00
  freemarker:
    suffix: .ftl
#    templateEncoding: UTF-8
    templateLoaderPath: file:D:/IdeaProjects/ht_tb_web/web_html/
    charset: UTF-8
    content-type: text/html;charset=UTF-8
#    default_encoding: UTF-8
    cache: false
    expose-session-attributes: true
    # 设置上下文路径
    request-context-attribute: request
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: wingzz00
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 100
        min-idle: 20
  cache:
    type: redis
  session:
    timeout: 86400 # Session 过期时间，单位s
mybatis:
  typeAliasesPackage: com.yao.sys.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
jwt:
  config:
    key: jsldkfuweio&*($@JHJBVDAYUIDhj
    ttl: 3600000
logging:
  level:
    com.yao.sys.dao: DEBUG
  config: classpath:logback-spring.xml
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false
#公共权限每个人都有
interceptor:
  noVerify: /welcome,/index,/,/loginOut,/info/index,/info/resetpwd,/text/frame
tb:
  file:
    url: D:\logs\tb\xlsxFile\
  khd:
    aes: NVHGIYTXGHKCPVVLWWDS
  dirPath: D:\logs\tb\xlsxData\


